spring-cloud-gateway:
#  hostport: httpbin.org:80
#  hostport: localhost:5000
#  uri: http://${test.hostport}
server:
  port: 9009
spring:
  application:
    name: spring-cloud-gateway
  jmx:
    enabled: false
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes: # 网关路由配置
        - id: spring-cloud-producer # 路由id，V自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://spring-cloud-producer # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/spring-cloud-producer/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: service-ribbon # 路由id，自定义，只要唯一即可
          uri: lb://service-ribbon # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/service-ribbon/** # 这个是按照路径匹配，只要以/user/开头就符合要求

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'